{
 "title": "Smart Home Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Power (desk downstairs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Power (W)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Plug under desk (router)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power (W)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power (TV)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Power (W)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "KP115 Temp for measuring",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power (W)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power (kitchen)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Power (W)" }
   ],
   "targets": [
    {
     "alias": "Kitchen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shellyplug-s-5AD8A5",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power (W)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power (desk upstairs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Power (W)" }
   ],
   "targets": [
    {
     "alias": "Desk upstairs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shellyplug-s-5A05FB",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power (W)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shellyht-706C2B",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Balkon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shellyht-706B54",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shellyht-706C2B",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Balkon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shellyht-706B54",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shelly H&T Battery",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shellyht-706C2B",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Balkon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shellyht-706B54",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heizung Schreibtisch Router",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Heizung Schreibtisch Router (Wohnzimmer)",
     "query": "SELECT mean(\"valveActualTemperature\") AS \"Valve actual temperature\", mean(\"valvePosition\") AS \"Valve position\" FROM \"Heizung Schreibtisch Router (Wohnzimmer)\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve actual temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "setPointTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve set temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "valvePosition" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve position" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heizung Essbereich",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Heizung Wohnzimmer Essbereich (Wohnzimmer)",
     "query": "SELECT mean(\"valveActualTemperature\") AS \"Valve actual temperature\", mean(\"valvePosition\") AS \"Valve position\" FROM \"Heizung Schreibtisch Router (Wohnzimmer)\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve actual temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "setPointTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve set temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "valvePosition" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve position" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thermostate (aktuelle Einstellung)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizung Schreibtisch Router (Wohnzimmer)",
     "select": [
      [
       { "params": [ "valvePosition" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizung Wohnzimmer Essbereich (Wohnzimmer)",
     "select": [
      [
       { "params": [ "valvePosition" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "s" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Thermostat Heizung Bad (Bad)",
     "select": [
      [
       { "params": [ "valvePosition" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heizung Bad",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Thermostat Heizung Bad (Bad)",
     "query": "SELECT mean(\"valveActualTemperature\") AS \"Valve actual temperature\", mean(\"valvePosition\") AS \"Valve position\" FROM \"Heizung Schreibtisch Router (Wohnzimmer)\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve actual temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "setPointTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve set temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "valvePosition" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valve position" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thermostate (Aktuell)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizung Schreibtisch Router (Wohnzimmer)",
     "select": [
      [
       { "params": [ "setPointTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Eingestellte Temperatur" ], "type": "alias" }
      ],
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Aktuelle Temperatur" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizung Wohnzimmer Essbereich (Wohnzimmer)",
     "select": [
      [
       { "params": [ "setPointTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Eingestellte Temperatur" ], "type": "alias" }
      ],
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Aktuelle Temperatur" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Thermostat Heizung Bad (Bad)",
     "select": [
      [
       { "params": [ "setPointTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Eingestellte Temperatur" ], "type": "alias" }
      ],
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Aktuelle Temperatur" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thermostate (24h)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Temperatur" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Heizung Schreibtisch Router (Wohnzimmer)",
     "select": [
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Heizung Wohnzimmer Essbereich (Wohnzimmer)",
     "select": [
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Thermostat Heizung Bad (Bad)",
     "select": [
      [
       { "params": [ "valveActualTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}